function Work() {
  
    return (
        <main className="exp">

            <div className="school">
                <h2>Education</h2>

                <ul>
                    <li>
                        <h3>B.S. Computer Science - University of Pittsburgh</h3>
                        <h4>Minor in Economics (2019-2023)</h4>
                        <p>Relavent coursework: Data Structures & Algorithms, Computer Organization & Assembly, Systems Software, Formal Methods, Operating Systems, Software Engineering, Web Development, Data Science, Quality Assurance, Cloud Computing, Applied Statistics, Analytical Geometry & Calculus</p>
                    </li>
                </ul>
            </div>
            
            <div className="work">
                <h2>Work Experience</h2>

                <ul>
                    <li>
                        <h3>Security Analyst L1 - A2 Secure</h3>
                        <h4>May 2022 - Present</h4>
                        <h5>Barcelona, Spain (remote)</h5>
                        <p>
                            Conduct detailed analyses regarding security incidents generated by various cloud
                            infrastructures (predominantly Azure and MS Defender, Elastic SIEM, Splunk,
                            Crowdstrike, GCP); verify and log case or escalate to L2 as necessary. Manage and respond to reports involving phishing and quarantined emails in order
                            to mitigate threat impact. Correspond effectively with SOC team about recent developments in protocol and
                            customer relations to ensure high quality service for all clients around the clock
                        </p>
                    </li>
                    
                    <li>
                        <h3>Lab Consultant - Pitt IT</h3>
                        <h4>July 2022 - October 2022</h4>
                        <h5>Pittsburgh, PA</h5>
                        <p>
                            Resolved technology dilemmas for peer students in the computer labs, including
                            computer, printer, and website services.
                            Monitored and maintained network of printers on University of Pittsburgh's campus,
                            ensuring minimal downtime and maximum effectiveness.
                        </p>
                    </li>
                </ul>
            </div>
            
        </main>
    )
}

export default Work